### ISSUE TITLE
Builder won't build underwater

### ISSUE THREAD

**Issue by drysdan** [McJtyMods/RFToolsBuilder#10]
1.15-2.0.0-alpha
Was pretty sure the Builder used to be able to place blocks under water or other replaceable blocks, but now it doesn't seem to. Tested with shape card for a shape half above, half below the surface of the water, and it only builds the part of the shape that's above water.

**Comment by AlexeyOplachko** [comment]
1.15-2.1.1-beta
Still happening, also related to shield projector. It's kinda annoying when trying to build base under water.

**Comment by McJty** [comment]
Fixed next release

**Comment by AlexeyOplachko** [comment]
Sorry to bother you, but does this fix affect only Builder or Shield Projector is included?

**Comment by McJty** [comment]
Shield Projector doesn't have this problem. Nothing to fix there

**Comment by AlexeyOplachko** [comment]
Just tested. If you generate shield and pour water after it can replace water when you turn it on/off with redstone. But it doesn't replace when you're trying to LMB it under water for the first time. 
Here's video with me testing. https://www.youtube.com/watch?v=hXdTqY0yR28

**Comment by McJty** [comment]
Well yes that's normal. Shield templates are solid blocks. They will replace water. Can't do anything about that. However the shield will properly go over water if you make the shield using a shape card

**Comment by AlexeyOplachko** [comment]
Sry, forgot to show that in vid, I used shape card for that

**Comment by McJty** [comment]
I don't really understand what you're trying to show in that video? Is there still a problem? If so can you clarify?

**Comment by AlexeyOplachko** [comment]
I place Shield Projector under water with Shape card, try to turn it on with lmb, nothing happens.
Same Shield Projector without water works. 
Also literally same course of actions on 1.12 version does work under water.

**Comment by McJty** [comment]
With lmb? I suppose you mean the smart wrench?

**Comment by McJty** [comment]
BTW. In the video I don't see you giving the shield projector any power

**Comment by AlexeyOplachko** [comment]
Sorry if I'm terrible at explaining things, English is not my native language, and I'm not that good at explaining even in my native language.
My usual course of actions to make a shield with RFTools Shield Projector

1. Place power source
2. Place Shield Projector
3. Insert Shape card with some sort of shape set up in it
4. Click with left mouse button on shield projector block
5. Shield composes
6. I set up redstone setting and all other stuff
7. I turn shield on/off

Depending on when water is added it has different result in 1.15.2.
Before step 5 shield doesn't compose at all, if after it(or no water at all) works properly including step 7.
On 1.12.2 doing same steps works regardless of when water is added.

Step 3 works with and without wrench on both versions for some reason, but I specifically rechecked using wrench and using wrench with right mouse button. 

> BTW. In the video I don't see you giving the shield projector any power

It was there under shield projector block, sorry again for not making it clear.

**Comment by McJty** [comment]
Left click is not supposed to work for composing a shield. It must be done by right clicking with the smart wrench

**Comment by AlexeyOplachko** [comment]
As I said I tried using wrench with right click. Same result, no shield under water.
And left click does work in 2 tested situation (water and no water) on 1.12.2 and only in no water situation on 1.15.2.

Edit: also got some screenshots. Tier 4 projector: 
![image](https://user-images.githubusercontent.com/45398541/82147723-6955dc00-9858-11ea-81bf-c74212b683d0.png)
 and shape card installed in it  
![image](https://user-images.githubusercontent.com/45398541/82147531-39a6d400-9858-11ea-9015-cf8410630a1d.png)

**Comment by McJty** [comment]
Well I just tried it myself and I can use the shield projector just fine underwater. Used a shape card and then right clicked with a wrench and the shield formed. No idea why it isn't working for you

**Comment by Kinishina** [comment]
Hi! Got curious and checked myself. Not working for me either. Shield seems not be able to replace water at all. Used wrench to activate if that's important.

![05-17_22-21-00_javaw](https://user-images.githubusercontent.com/65353723/82158065-0d0daf00-988e-11ea-86d2-97b6769380bc.png)

Last available versions of everything, clear modpack: mcjtylib-1.15-4.1.0-beta, rftoolsbase-1.15-1.1.1-beta, rftoolsbuilder-1.15-2.1.1-beta, rftoolspower-1.15-2.1.1-beta

**Comment by McJty** [comment]
Well I don't understand this. Here is a setup I made myself (on 1.15.2). Using a shape card. If you look well enough you can see the shield blocks are also placed under water:
![2020-05-18_09 50 05](https://user-images.githubusercontent.com/8188472/82187767-327dd580-98ed-11ea-8da4-f31c36820752.png)

**Comment by McJty** [comment]
So I have no clue why it wouldn't be working for you...

**Comment by AlexeyOplachko** [comment]
Here's archive with map, and basic instance on which I tested. Maybe you'll be able to see something in there. 
[Test15.zip](https://github.com/McJtyMods/RFToolsBuilder/files/4642912/Test15.zip)
Forge version latest atm(31.2.0) 
Mod versions:

- mcjtylib-1.15-4.1.0-beta.jar
- rftoolsbase-1.15-1.1.1-beta.jar
- rftoolsbuilder-1.15-2.1.1-beta.jar
- rftoolspower-1.15-2.1.1-beta.jar
- rftoolsutility-1.15-2.1.1-beta.jar

**Comment by AlexeyOplachko** [comment]
In new release this is finally working, thanks :)
