### ISSUE TITLE
[1.18.2] Builder Dupe Bug (a different one)

### ISSUE THREAD

**Issue by sme23** [McJtyMods/RFToolsBuilder#100]
Copying a space chamber containing a wither with a space card in a builder will spawn the wither and then place the 3rd head, duplicating it.

Space Chamber containing Wither structure:

![2022-06-20_00 35 02](https://user-images.githubusercontent.com/24559482/174526291-ff487a44-e651-46c6-bc6b-fe71bfab56e2.png)

Copied via Builder with Shape Card:

![2022-06-20_00 35 06](https://user-images.githubusercontent.com/24559482/174526333-10054f29-a026-4b7f-90bb-7deea52b1bfd.png)

With 4 Soul Sand and 3 Wither Skeleton Skulls in the above chest, pulling the lever spawns a wither and leaves an additional head behind:

![2022-06-20_00 35 25](https://user-images.githubusercontent.com/24559482/174526437-6107b723-592f-4a68-9e25-ac9d61abcff8.png)

**Comment by McJty** [comment]
Version?

**Comment by sme23** [comment]
1.18-4.0.12

**Comment by McJty** [comment]
Hmm not sure how to reproduce this as I have no idea how to make that wither structure without it spawning?

**Comment by McJty** [comment]
ah nm. Found it

**Comment by McJty** [comment]
Ok, I can reproduce it

**Comment by McJty** [comment]
Bug will be fixed in the next release (probably this evening)
