### ISSUE TITLE
1.18.2: Dark Pedestal from ProjectE causes RFTools Builder to stop at that location

### ISSUE THREAD

**Issue by James103** [McJtyMods/RFToolsBuilder#101]
To reproduce:
1. Create a new Forge 40.1.31 instance with Minecraft version 1.18.2
2. Install rftoolsbase-1.18-3.0.9
3. Install rftoolsbuilder-1.18-4.0.12
4. Install mcjtylib-1.18-6.0.15
5. Install ProjectE-1.18.2-PE1.0.1
6. Install a mod to provide energy, such as Mekanism, Immersive Engineering, or similar.
7. Install all dependencies of the above mods if any.
8. Start the created instance with the mods installed.
9. Create a new world with cheats enabled.
10. Give yourself an RFTools Builder, a Shape Card (Quarry, Clearing Quarry, or Clearing Silk Quarry), a source of energy, and a chest to store the output from the builder.
11. Place the RFTools Builder down, place a Chest on top of the Builder, and place the energy source next to the Builder.
12. Give yourself a Dark Matter Pedestal from ProjectE and place it down somewhere.
13. With the Shape Card (Quarry) in your hand, select the builder once to start the area selection, then select the pedestal twice to define both endpoints and finish the selection.
14. Place the Shape Card inside the Builder, then power the Builder to start it.
15. The builder should stop immediately with "not enough power" regardless of its charge level and settings.

This is caused by the Dark Matter Pedestal from ProjectE quite literally having the hardness of a million stone blocks in one.
This hardness value is too much for the Builder to handle, so it stops with "not enough power" and will not continue until the pedestal is removed.

Such blocks (with hardness in the thousands or higher) should be blacklisted by the Builder for being too hard to break, in addition to blocks with negative hardness (game considers these blocks unbreakable) and blocks specifically made unbreakable by fake players.

**Comment by McJty** [comment]
In the builder of the gui (the six buttons) there is a button that you can press that will make the builder skip such blocks

**Comment by James103** [comment]
> In the builder of the gui (the six buttons) there is a button that you can press that will make the builder skip such blocks

I just tested this, and the state of the "wait if operation not possible" button (or any of the five other buttons in that block) does not matter. The builder will simply stop when it gets to the Dark Pedestal simply because it has a finite (albeit very large) hardness such that even the Builder with maximum upgrades at default settings is unable to hold a big enough charge to allow the block to be broken.

**Comment by McJty** [comment]
Hmm I have to check that but it should skip that block. Maybe something got broken

**Comment by James103** [comment]
It's not just the Dark Pedestal from ProjectE that is affected. Any block with a hardness value greater than a value determined by the maximum charge of the Builder divided by the minimum cost to break a block of 1 hardness (both configurable) will always cause the Builder to stop there with "not enough power".

**Comment by McJty** [comment]
I will solve this by making sure that these kinds of extremely hard blocks are potentially also skipped

**Comment by McJty** [comment]
Fixed in the upcoming version
