### ISSUE TITLE
McJtyLib 1.18-6.0.10 Builder is not replacing lava blocks with dirt...can I just copy the FluidTools.class from the fixed 1.16-5.1.8 jar?

### ISSUE THREAD

**Issue by DrWho1977** [McJtyMods/RFToolsBuilder#103]
I saw that this issue was patched in version 1.16-5.1.8 but I am still experiencing this issue in All the Mods 7, which is using McJtyLib 1.18-6.0.10.   I am playing single player so I was wondering if I should just copy the fixed FluidTools.class file from the old 1.16 version into the McJtyLib 1.18 JAR file on my PC?  Thanks for the help.

**Comment by DrWho1977** [comment]
I think I found the answer to the question myself by looking at the code, the answer is no.  It looks like the import statements have changed between the two versions of the FluidTools.class file.  However it does look like one could fix the code in the function called FluidStack pickupFluidBlock the same way that iTitus did in his fix here:  https://github.com/McJtyMods/McJtyLib/pull/135/files#    however I would have to download JDK to recompile but I'm not even sure you mod author guys like people doing that kind of stuff and I'm not even sure the Curseforge mod launcher wouldn't undo my changes or throw an error code when I launched minecraft because it detected changes or something.  So I'll leave it to the professionals.  Thanks for any help or advice you can offer.

**Comment by McJty** [comment]
Fixed next release
