### ISSUE TITLE
max build height

### ISSUE THREAD

**Issue by ThirtyTwelveNor** [McJtyMods/RFToolsBuilder#104]
shape cards has max build height of 256(only tested silk quarry)
while it should be from -64 to 320
https://discord.com/channels/403871125206990849/403871125941256193/1004800178361991218
video of typing 999

im playing 
All the Mods 7-0.4.23
forge-1.18.2-40.1.60
rftoolsbase-1.18-3.0.9.jar
rftoolsbuilder-1.18-4.0.13.jar

**Comment by McJty** [comment]
Fixed next release
