### ISSUE TITLE
1.19.2 Shape Card can't be configured correctly

### ISSUE THREAD

**Issue by Chr0n4s** [McJtyMods/RFToolsBuilder#108]
The height of the area has a limit of 256 but that is not the correct build height for newer minecraft versions.
Every time i configure the area in the GUI the height gets restricted to 256.
Configuring with in world selection functions correctly. As soon as i change something in the GUI the height gets restricted to 256.

**Comment by Ninjawolf0007** [comment]
Came here to post the same thing. I noticed this in the ATM8 modpack. The Quarry Card (and perhaps any card?) does not fit the true build height anymore.

**Comment by Mihoshika** [comment]
Best you can do is run it twice at different Y levels. Though, for most cases, you won't need to run at full 256. For ATM Mining Dimension, you'll probably want a chunk destroyer anyways.

**Comment by Gazzoo-byte** [comment]
If the purpose is for the ATM8 mining dimension I think you can circumvent this by setting the y offset to -126 or so, from testing different values while configuring it myself

**Comment by beerik94** [comment]
I have this problem as well in ATM8 modpack version 1.0.15 with RFToolsBuilder version 1.19.1-5.3.2

**Comment by McJty** [comment]
Will be fixed next release
