### ISSUE TITLE
Builder clear mekanism upgrades.

### ISSUE THREAD

**Issue by Biotoxick** [McJtyMods/RFToolsBuilder#110]
Issue description: 
Builder clear mekanism upgrades.

Steps to reproduce: 

1: Build a mekanism system, (in our case, 6 full height brine tower, heavy water pumps and all needed mekanism machines to produce D-T Fuel).
2: Make a space card of this build to copy it.
3: Put this card in the builder then give him fully upgraded mekanism machines (pumps, infuser, rotary condensentrator ect...).
4: Then launch the builder, it will place all blocks at the good spot but it will totally delete all upgrades inside the given machines.

Versions:

Minecraft: 1.18.2
Forge: 40.1.92
McJtyLib: 6.0.19
RFTools: 3.0.11
RFTools Builder: 4.0.16
Mekanism: 10.2.5.465

Modpack: Biotocube 1 1.0.14

I didn't get the server log file but the issue appear 2 times and on all mekanism machines.

**Comment by McJty** [comment]
yes that's normal. RFTools Builder has no way to copy those upgrades. That's not something that is possible I'm afraid

**Comment by Biotoxick** [comment]
Ok, thanks a lot for your answer, we will put upgrades by hand :)
