### ISSUE TITLE
[Bug][1.18.2]The builder can not work on copy mode, offset option of space card can not work.

### ISSUE THREAD

**Issue by ghost** [McJtyMods/RFToolsBuilder#119]
As the title, the builder can not work on copy mode, offset option of space card can not work.

**Steps**
1. Bind the space card to the space chamber controller.
![2023-11-26_22 40 36](https://github.com/McJtyMods/RFToolsBuilder/assets/115923988/c2293100-4a12-4c5d-a71a-7cbd3f5ca89f)
2. Insert the space card into the builder. The settings of the builder are shown in the figure.
![2023-11-26_22 41 30](https://github.com/McJtyMods/RFToolsBuilder/assets/115923988/e2bd984d-2d51-40b8-af92-b367846475c4)
3. Set offset option of the space card.
![2023-11-26_22 41 41](https://github.com/McJtyMods/RFToolsBuilder/assets/115923988/7db7fef1-6d3c-4ac6-971f-47cc6cd43e4a)
4. Start the builder. See error: The builder can not work on copy mode. In other modes, the offset setting option also does not work.
![2023-11-26_22 44 34](https://github.com/McJtyMods/RFToolsBuilder/assets/115923988/80540d87-16da-4ebf-99ff-7da1381f824a)

**Environment**
 - Mod Version: 4.1.3
 - Forge Version: 40.2.10
 - Operating System: Windows 10
 - Other Mods: McJtyLib(v6.0.20), RFTools Base(v3.0.11), RFTools Power(v4.0.9), RFTools Utility(v4.0.23), RFTools Storage(v3.0.12), RFTools Control(v5.0.10).

**Comment by McJty** [comment]
What? That doesn't make sense. You cannot use both a shape and a space card. It's one or the other. What are you even doing with that space card after you set the option? I don't understand

**Comment by ghost** [comment]
> What? That doesn't make sense. You cannot use both a shape and a space card. It's one or the other. What are you even doing with that space card after you set the option? I don't understand

If the offset option cannot be applied to the space card, does it mean that the blocks generated by the builder must appear behind the builder?
I remember in version 1.12.2, the position of the generated blocks could be specified by setting the offset option of the space card.
Or, what should I do if I want to freely specify the position of the blocks generated by the builder?

**Comment by McJty** [comment]
The space card is more limited. It can only work behind the builder

**Comment by ghost** [comment]
> The space card is more limited. It can only work behind the builder

OK，I understand, thank you. So all that remains is the issue of copy mode not working.

**Comment by McJty** [comment]
Well I see no chest with building materials on top of the builder. The builder will not cheat in blocks. It needs blocks in order to make the copy

**Comment by ghost** [comment]
> Well I see no chest with building materials on top of the builder. The builder will not cheat in blocks. It needs blocks in order to make the copy

Thank you. I misunderstood. I will close this issue.
