### ISSUE TITLE
Clearing Quarry places dirt

### ISSUE THREAD

**Issue by TehFoxFire** [McJtyMods/RFToolsBuilder#12]
Forge 31.1.30
Server
rftoolsbuilder-1.15-2.0.1-alpha

**Comment by McJty** [comment]
I cannot reproduce this. Can you give me a bit more information? Show me the gui's of the builder? Show me what shape card you used?

**Comment by TehFoxFire** [comment]
https://i.imgur.com/Rpg9mnN.png
https://i.imgur.com/x49DGF5.png
https://i.imgur.com/SInmH04.png
https://i.imgur.com/iuUK0Oh.png

**Comment by McJty** [comment]
Ok, that's weird... Can't see why it isn't working for you

**Comment by TehFoxFire** [comment]
ok, strange. After a server restart and a on/off toggle it cleared the chunks of dirt..However its in a minecolonies claim and cant mine now. Is there a way to add the builder to permissions? Can I add the fake player?
