### ISSUE TITLE
Shield Projector - Shield breaks from water

### ISSUE THREAD

**Issue by Spaex** [McJtyMods/RFToolsBuilder#121]
Hi, 

I use a Shield Projector to protect a base from hostile mobs entering.
A creeper showed me (by exploding next to water) something I don't think is intentional. 
If water flows against the projected Shield it passes through the shield and "destroys" the Shield until you deactivate the projector and activate it again. 

Would be cool to make it waterproof and to regenerate itself if it gets broken somehow. 

Short GIF to visualize the problem: 
![ezgif-5-b4fba950b0](https://github.com/McJtyMods/RFToolsBuilder/assets/46825907/1ce062ba-deb1-4671-b4af-f8be10eb3ffb)

**Comment by Khunkurisu** [comment]
Bump, as this is still an issue (was going to use the shield as a door for an underwater base :<)

**Comment by McJty** [comment]
For what version?

**Comment by Khunkurisu** [comment]
Sorry, I should’ve included that to begin with!
Minecraft version 1.20.1 RFToolsBuilder version 1.20-6.0.5

of note it’s part of a modpack but if necessary I could test that version alone with no mods or config changes later

**Comment by McJty** [comment]
Update the mod. This has been fixed
