### ISSUE TITLE
builder in quarry mode does not pick up drops from AE2's certus quartz cluster

### ISSUE THREAD

**Issue by lennyservant** [McJtyMods/RFToolsBuilder#122]
MC Version: 1.20.1
Mod Version: 1.20-6.0.3

the builder in quarry mode doesn't pick up any drops when mining the certus quartz cluster from AE2

i think this is because the builder's `LootContextParams.THIS_ENTITY` [is null when mining](https://github.com/McJtyMods/RFToolsBuilder/blob/f0fd4c018003bb364dafffd44404fcc0c94a0aa9/src/main/java/mcjty/rftoolsbuilder/modules/builder/blocks/BuilderTileEntity.java#L1225C29-L1225C29)

certus quartz cluster's `getDrops` [here](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/137cb538538b7ef9c66261931f662182ddf937b4/src/main/java/appeng/decorative/solid/CertusQuartzClusterBlock.java#L67C6-L67C6) returns an empty list when `LootContextParams.THIS_ENTITY` is null

**Comment by McJty** [comment]
Can't do much about that I'm afraid

**Comment by McJty** [comment]
Fixed and thanks for the PR
