### ISSUE TITLE
X/Y/Z labels in shape card

### ISSUE THREAD

**Issue by void-spark** [McJtyMods/RFToolsBuilder#127]
Hi!

Based on observations on 1.19 (ATM8)
Another probably too much work for the benefits one, but would it be possible to show x/y/z labels in the Shape card? :)
It would help a lot not having to guess which-one is which, especially for first time users :)

**Comment by McJty** [comment]
I could do that but it's not hard to guess given that X/Y/Z are always represented in that order. i.e. first is X, second is Y and third is Z

**Comment by void-spark** [comment]
Fair enough, I think in my case I get confused more because I work with 3d programs as well, and then z is up, so I find it strange up is the middle one, but then labels wouldn't help there :)

**Comment by McJty** [comment]
Well that's just Minecraft convention that uses Y for down/up
