### ISSUE TITLE
Power limit of 20k / face? Not enough to stop builder from complaining about power

### ISSUE THREAD

**Issue by void-spark** [McJtyMods/RFToolsBuilder#129]
Hi!

Based on observations on 1.19(ATM8)

We noticed that when mining something big with a clearing quarry card, we could not get enough power in the block to keep it running without it complaining about lack of power.
We were feeding with mekanism top tier universal cable,
Connecting one side only allowed 20k/tick of power to be drawn, much less then was available or the wire could transport.
Connecting all sides except the one with the output box worked a lot better, but still the error kept showing on the machine.

It would be nice if it was at least possible to push enough power in the machine for it to run without error :)

**Comment by McJty** [comment]
Did you infuse the builder? It is more efficient then

**Comment by McJty** [comment]
But other then that. That's the limitation. The Builder is OP already as it is

**Comment by void-spark** [comment]
I didn't realise there was something called infusing, I'll look into that! :)
And it is a very scary/op machine, so I'll accept that :)
