### ISSUE TITLE
Vehicle Builder within ATM9

### ISSUE THREAD

**Issue by Ploopysnoof** [McJtyMods/RFToolsBuilder#131]
Hi,
My vehicle builder has a space card linked to a space chamber, and the create button does light up. Yet when I try to create the vehicle, nothing happens. Am I doing something wrong?

https://github.com/McJtyMods/RFToolsBuilder/assets/165073042/f6be9ad4-b806-494e-bd90-6aad230dfbb7

**Comment by McJty** [comment]
Is your space chamber correctly formed? I think the problem is there but I can't see it since you don't show that well in your video

**Comment by Ploopysnoof** [comment]
It was not formed, thanks for answering. The version of atm9 I am playing doesn't have the vehicle guide on the manual so I was confused. Thanks
