### ISSUE TITLE
1.20.1 Crashes on load

### ISSUE THREAD

**Issue by ModernGamingWorld** [McJtyMods/RFToolsBuilder#133]
![2024-04-23_01 06 05](https://github.com/McJtyMods/RFToolsBuilder/assets/75923060/c8bffccc-4240-41f3-b821-fe0e53fa9273)

**Comment by McJty** [comment]
Versions please? Of McJtyLib, RFToolsBase, RFToolsBuilder

**Comment by vizthex123** [comment]
same crash here!

log:
[latest.log](https://github.com/McJtyMods/RFToolsBuilder/files/15072471/latest.log)

also, the CF pages don't have a quick link to the issue trackers.


> Versions please? Of McJtyLib, RFToolsBase, RFToolsBuilder

mine happened after the latest update.

Lib: 8.0.4
Base: 5.0.3
Builder: 6.0.4
Utility: 6.0.6

**Comment by McJty** [comment]
CurseForge hasn't updated RFToolsBuilder yet. Still under review. Just wait until it gets updated
