### ISSUE TITLE
 No visible cube at the shape card in the Mod RFTools Builder (Quarry)

### ISSUE THREAD

**Issue by Buggy1987** [McJtyMods/RFToolsBuilder#135]
Hello, i have no visual effects at the shape card in the MOD RFTools Builder.
I can set DIM and Offset and so on but i dont see the visual effects at the right corner of the ui.
I have already tested to update all the mods inclusive the McJtyLib to the newest version. No fix
The Mod is installed in the direwolf20 1.20 pack

**Comment by McJty** [comment]
This is known. That feature has simply not been ported yet. So not really a bug
