### ISSUE TITLE
[1.20.1] Selected Shape Area is not pre-viewable

### ISSUE THREAD

**Issue by RavinClaw** [McJtyMods/RFToolsBuilder#137]
When trying to look at the preview it just does not appear at all, is this a bug or a feature?

![image](https://github.com/user-attachments/assets/8c857a6c-6848-4d85-817d-2a7a7a733488)

^^^
Screenshot from 1.20.1 Multiplayer with Rftools Builder version `1.20-6.0.5`

**Comment by TheoXsp** [comment]
same issue here

**Comment by McJty** [comment]
Simply not implemented
