### ISSUE TITLE
getCurrentBlock should not be able to return null without null checking in place where it is called.

### ISSUE THREAD

**Issue by Vaelzan** [McJtyMods/RFToolsBuilder#14]
https://github.com/McJtyMods/RFToolsBuilder/blob/d1553a605ef153d8bf47aa89ff5a0ddcc018e24a/src/main/java/mcjty/rftoolsbuilder/modules/builder/items/ShapeCardItem.java#L248

Currently, it's entirely possible to get a crash because getCurrentBlock can return null and then is immediately assumed to be not null (eg. line 85 and 97 of the same file).

I don't have a crash log because this was reported by a user of a mod pack I maintain, and they didn't send one through to me. I was just able to spot this after they sent a screenshot.

**Comment by McJty** [comment]
In practice this cannot really cause a problem because getCurrentBlock will never return null given the 'if' branch that we're in. But for absolute safety I'll test for this anyway

**Comment by Vaelzan** [comment]
In practice this did cause a crash, thus why I reported it. Unfortunately, I don't have the original screenshot anymore to show more evidence, because this was nearly a month ago now.

**Comment by Vaelzan** [comment]
Actually, never mind, was able to find it by searching Discord with that date. Figured I might as well show it since it may be that there is another issue somewhere, if it isn't meant to be able to return null. https://i.imgur.com/oLBrZto.png

**Comment by McJty** [comment]
That stacktrace doesn't really say much since the code has changed too much. Is that even for the 1.15 version?

**Comment by Vaelzan** [comment]
It says 1.15-2.0.1-alpha right there in the pic. I believe at the time it was Forge 31.1.49. But as I said, they didn't send me the log nor crash report, so I'm doing the best I can with the information I have available. The only other thing that they mentioned other than that they were using the latest pack release at the time (thus me knowing the Forge version) is that it occurred as soon as they used the shape card on the builder.

However, the main purpose of attaching that was to show that it was indeed a problem in the wild at the time. You would know far better than I what changes you've made since the 2.0.1 release of RFTools Builder to see if it's still likely to be an issue or if it may have been resolved elsewhere.
