### ISSUE TITLE
[1.20.1] RFTools Space Card and dimensionnal chamber not working.

### ISSUE THREAD

**Issue by Nagispace** [McJtyMods/RFToolsBuilder#141]
Issue description: Sneak right clicking a Space Chamber Controller with a space card will increment the channel of the space card to n+1 causing the space chamber, space card and all its builder related feature to not work.

Steps to reproduce: 

1) Place valid space chamber setup.
2) Sneak right click the controller with the space card
3) Channel on the space card is now incremented by one
4) Break and replace the controller, sneak right click again and the channel of the card is incremented by 1 again but the channel of the controller is still "0"

Versions:
* Minecraft: 1.20.1
* Forge: 47.2.20
* McJtyLib: 1.20-8.0.5
* RFToolsBase: 1.20-5.0.4
* RFToolsBuilder: 1.20-6.0.5

Modpack is AllTheMods 9 To The Sky version 1.1.0

Relevant logs, if any: No Relevant logs

**Comment by McJty** [comment]
Hmm. If I break the controller it disappears (which is another bug). So how did you get to do that. I don't exactly understand what you are doing. Did you place a new controller? Did you then reform the space chamber? More details please

**Comment by Nagispace** [comment]
Here are some screenshots :
New Controller and space card with no channel :
![image](https://github.com/user-attachments/assets/4e018f04-8dfd-40b8-acfc-bf548cc256b1)
![image](https://github.com/user-attachments/assets/870e243e-8652-4bc2-8194-6d682d98243e)

Placing the controller to form a space chamber :
![image](https://github.com/user-attachments/assets/a8a53020-e166-4270-8b3b-fb9b99e58e12)
Space Card after sneak right clicking the controller (I already used this world to test it so the channel is already high but it starts at 1) :
![image](https://github.com/user-attachments/assets/949e9168-bafc-4cd2-a8a8-8ddb1100ae15)
After mining the space chamber controller with a netherite pickaxe, channel is still "0" :
![image](https://github.com/user-attachments/assets/49af6029-4321-45c7-b779-567eb4aba431)
Placing it again at the same place :
![image](https://github.com/user-attachments/assets/da5c2d92-d528-47a3-a762-a16a55a0ad62)
Sneak right clicking with the space card on the controller opens this GUI (the "open manual" button does nothing):
![image](https://github.com/user-attachments/assets/91b2bf04-410a-4a04-97ce-6843a932d213)
The channel of the space card is now incremented :
![image](https://github.com/user-attachments/assets/d34fadce-bdee-4c7b-9672-8bcb007eadde)
Repeating the "breaking and replacing controller then sneak right clicking with a space card" process will increment the channel on the space card
![image](https://github.com/user-attachments/assets/22aab8e3-862f-4518-82fb-6076169d9501)

**Comment by McJty** [comment]
I don't understand how you could mine the controller...

**Comment by McJty** [comment]
I'll first fix the breaking bug and will try it after that.
My guess it though that the space chamber channel will have updated. It's a pity you don't have TOP installed as it would show you the channel of the space chamber controller

**Comment by Nagispace** [comment]
> TOP

TOP ? What is that ? I can install it to check it

**Comment by McJty** [comment]
The One Probe. One of my other mods

**Comment by Nagispace** [comment]
Installed TOP 10.0.2

According to TOP the channel is correctly matched between the card and the controller but the GUI still pops up and show the space info that came from another minecraft save until the chamber is formed.
I am really sorry for all this but the issue I had was because I didn't "form" the chamber by right clicking with the smart wrench (it should be stated in the 'shift' description that it's needed or have its relevant infos in the ingame manual)
Having TOP helped me see that. The controller still drops when mined.
