### ISSUE TITLE
Lava eats thru shield projection in 1.20.1

### ISSUE THREAD

**Issue by 19PHOBOSS98** [McJtyMods/RFToolsBuilder#145]
![2024-09-04_14 28 33](https://github.com/user-attachments/assets/2ddf046c-6cca-496e-8bfd-2eca3c7d75e8)

**Comment by 19PHOBOSS98** [comment]
![2024-09-05_06 03 12](https://github.com/user-attachments/assets/0b39b5ff-327e-440e-a6b1-2b1abc17f7ff)
looks like water does the same

**Comment by 19PHOBOSS98** [comment]
made a pull request for it:
https://github.com/McJtyMods/RFToolsBuilder/pull/149/commits/9778c1e11829bce183ef1f5585630a62f27c9156

**Comment by DADA30000** [comment]
well it was merged so I think you can close it?

**Comment by 19PHOBOSS98** [comment]
oh right, sorry
