### ISSUE TITLE
Update RFBuilder 6.0.6 cause on Break the RF Builder Item disappearing

### ISSUE THREAD

**Issue by LeCyreaxYT** [McJtyMods/RFToolsBuilder#150]
I have Testet that the RF Tools Builder on Version 6.0.6 will disappearing the Item if i break the Builder. I Testet alot of Wrenches and Pickaxes all of them will not work. 

Then i downgradet to 6.0.5 and the Block Item will not disappearing after Break the Block.

I dont saw any errors or something and an mod conflict i cant see here.

**Comment by LeCyreaxYT** [comment]
Testet Version on 1.20.1

**Comment by McJty** [comment]
I will fix this. Thanks for reporting

**Comment by McJty** [comment]
Fixed in 6.0.7
