### ISSUE TITLE
Opening Shape Card GUI while in Builder disconnects client.

### ISSUE THREAD

**Issue by weirdchildren** [McJtyMods/RFToolsBuilder#152]
Pretty much what it says in the title.

Here is the part of the log that I thought was maybe useful[https://mclo.gs/O9jaIVc](url)

Using Version 1.21-6.0.2 Playing ATM10 ver 2.0

**Comment by rocascent** [comment]
i got a same issue.
and some error when opening the gui
![图片](https://github.com/user-attachments/assets/41d4c58e-080c-4e18-9326-096cc10e6985)

**Comment by McJty** [comment]
Fixed next version
