### ISSUE TITLE
Shield projector not affecting certain mobs

### ISSUE THREAD

**Issue by AlexeyOplachko** [McJtyMods/RFToolsBuilder#17]
1.15-2.1.1-beta
I have a shield projector set up to Solid Damage to everything except few players, it works most of the time, unless mob trying to go through is a: Dolphin, Squid or a Bat. 
Did additional testing, also includes: Bees, all types of fish, villagers, vex(but I'd assume it's normal)

**Comment by McJty** [comment]
Will be fixed next release
