### ISSUE TITLE
NPE after I tried to open the quarry card GUI from within Builder

### ISSUE THREAD

**Issue by xenoflot** [McJtyMods/RFToolsBuilder#22]
Issue description:  
NPE after I tried to open the quarry card GUI from within Builder.  Crash is not immediate; torches still flicker and wandering trader keeps on vocalising. It's only after you try to interact with the client again that something realises that a task has hung.

This is in the Enigmatica 5 mod pack. It's happened twice. in the process of setting up another instance to test in isolation.

Steps to reproduce: 
1. Place a Builder
2. Shift-click a Clearing Fortune Quarry card on the builder
3. Select two blocks at opposite corners of a single chunk, about 10 z-axis apart
4. Right-click install to the builder
5. Open Builder GUI, turn on preview
6. Exit builder and check the preview is good
7. Reopen Builder GUI and click "Open card GUI"
8. Game freezes with eventual crash.

Versions:
* Minecraft: 1.15.2
* Forge: 31.2.0
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:  mcjtylib-1.15-4.1.0-beta
* RFTools: rftoolsbuilder-1.15-2.1.2-beta  rftoolsbase-1.15-1.1.1-beta
 

Possibly incompatible mods and versions: 

Relevant logs, if any: 
https://gist.github.com/xenoflot/472efc6d6171e40e86f97960c541957f

**Comment by xenoflot** [comment]
I can verify that it also happens in a stripped down instance with just the above, plus JEI and Powah.

**Comment by McJty** [comment]
Probably fixed in the next release of McJtyLib

**Comment by NielsPilgaard** [comment]
I don't think this issue is fixed: The gui no longer gets displayed, more details here: https://github.com/NillerMedDild/Enigmatica5/issues/352

No mention of what goes wrong in the latest.log sadly.

**Comment by NielsPilgaard** [comment]
It looks like `[Thread-33/INFO]: Block file not found: rftoolsutility:timer` is printed in the log when the issue occurs.
