### ISSUE TITLE
[1.15-2.1.2-beta] Builder voiding blocks if there's no chest on top.

### ISSUE THREAD

**Issue by xenoflot** [McJtyMods/RFToolsBuilder#23]
All in the subject, really. I've tested both in Enigmatica5 and in a testing instance and if there's no chest on top of the builder, it mines but produces nothing. Pop a chest on top and it's working as intended.

Versions:

    Minecraft: 1.15.2
    Forge: 31.2.0
    CompatLayer (only if on Minecraft 1.10 or 1.11):
    McJtyLib: mcjtylib-1.15-4.1.0-beta
    RFTools: rftoolsbuilder-1.15-2.1.2-beta rftoolsbase-1.15-1.1.1-beta

**Comment by McJty** [comment]
I can reproduce this. I'll implement a fix

**Comment by McJty** [comment]
Fixed for next release
