### ISSUE TITLE
[1.15.2] Builder is in another dimension?

### ISSUE THREAD

**Issue by davqvist** [McJtyMods/RFToolsBuilder#27]
RFTools Builder 2.1.8
Forge 31.2.31

If I shift right click the builder with the quarry shape card to set the dimensions and then right click on any other block I get the message "Builder is in another dimension" even standing right next to it. I also can't shift right click the builder anymore to start over. Happens with other shape cards like the pump too. Manually setting the size of the shape card by right clicking the air works though.

**Comment by McJty** [comment]
Will be fixed next release. Thanks for reporting
