### ISSUE TITLE
[1.15.2][Issue] Selecting Blocks segments with Cards not working

### ISSUE THREAD

**Issue by jonnygrove** [McJtyMods/RFToolsBuilder#28]
I just updated to builder version 2.1.8 and noticed the that selecting block sections with the builder is no longer working. Neither the shape card, quarry, or pump cards work properly to make a block selection. When you Right-Click the card on the builder, I still get the message "Now select the first corner" but you get the message "The Builder is in another dimension!" when trying to make a selection - even though I never went to a different dimension. This message doesn't go away, even when trying to shift-click with a card to clear settings.

The cards still function normally when inserted in the builder.

I tried this on a fresh profile with just the RFTools mods. Builder versions 2.1.6-2.1.8 all give this error.

**Comment by McJty** [comment]
This should be fixed if you update
