### ISSUE TITLE
Shield Projector no longer holds RF.

### ISSUE THREAD

**Issue by BranMuffinz** [McJtyMods/RFToolsBuilder#29]
In the latest version for 1.15, **rftoolsbuilder-1.15-2.1.9**, the Shield Controller displays an RF capacity of 0. RF which was previously in the machines, before the update, is now gone, resulting in the current RF displaying as "0 / 0". Power cannot be put into the machines, and the machines can not have the power they need to operate, so they are effectively non-functional.

**Comment by McJty** [comment]
Yes I made a mistake there. I will fix this for the next version

**Comment by McJty** [comment]
Fixed now
