### ISSUE TITLE
Received invalid discriminator messages in multiplayer / Shape Card UI / Builder rendering

### ISSUE THREAD

**Issue by Draradech** [McJtyMods/RFToolsBuilder#3]
== **Builder** ==
**Clean (Forge + McJtyLib + RFToolsBase + RFToolsBuilder):**
Whenever the Builder is in view in multiplayer, server console shows [Server thread/FATAL] (https://pastebin.com/taeLpmZs) ~4 times per second. Message stops when destroying the builder or looking the other way. The status text above the builder (which works in singleplayer) is missing.

**All the Mods 4 v0.21:**
Whenever the Builder is in view in multiplayer, server console shows "Received invalid discriminator byte 52 on channel rftoolsbase:rftoolsbase" ~4 times per second. Message stops when destroying the builder or looking the other way. The status text above the builder (which works in singleplayer) is missing.

== **Shape card** ==
Shape card (clearing quarry, but probably all of them) UI doesn't update preview render or number of blocks in multiplayer. When editing one of the fields, the server console shows "Received invalid discriminator byte 12 on channel rftoolsbuilder:rftoolsbuilder" (once per keystroke). Singleplayer works fine.

If the shape card UI has not been open in singleplayer before, the server console shows an additional "Received invalid discriminator byte 14 on channel rftoolsbuilder:rftoolsbuilder" (~4 times per second).

Shape card behaviour of clean and ATM4 is identical.

Possibly related: https://github.com/McJtyMods/RFTools/issues/1989

Versions (clean and ATM4):
* Minecraft: 1.14.4
* Forge: 28.1.90
* McJtyLib: 3.5.12-alpha
* RFToolsBuilder: 1.2.8-alpha
* RFToolsBase: 0.0.9-alpha

Full server log of the clean run:
https://pastebin.com/izyUJ5jk
Between [17Nov2019 21:22:01.320] and the next login I had the shape card UI open and looked at a Builder in singleplayer.

**Comment by McJty** [comment]
Thanks for the detailed issue. This has been reported before but for now the solution has eluded me

**Comment by McJty** [comment]
Last update should fix this. Let me know if it doesn't and show me the full server log in that case

**Comment by RakSrinaNa** [comment]
Looks like it is fixed for me, didn't see it again with the crafter.

Also fixed the issue of the PacketCrafter being deserialized into another Packet class 👌

**Comment by Draradech** [comment]
Fixed here as well. Builder and Shape Cards work in ATM4 (+ your updates) now. Thanks for the quick fix!
