### ISSUE TITLE
Builder with shape card opens an invisible UI which can't be closed

### ISSUE THREAD

**Issue by Letoric** [McJtyMods/RFToolsBuilder#30]
MC: 1.16.3
Forge 34.1.0
Mod: 1.16-3.0.6
Base: 1.16-2.05
Power: 1.16-3.0.6

Topic pretty much says it all. 
Producible in ATM6 1.16.3 preview 2 pack.
Producible with only your mods (library plus all RF mods) and JEI

**Comment by McJty** [comment]
Known bug. No known solution right now

**Comment by McJty** [comment]
Will be fixed next release. I finally found it
