### ISSUE TITLE
[1.16.3] Server crash

### ISSUE THREAD

**Issue by WhitePhant0m** [McJtyMods/RFToolsBuilder#31]
[Crash Log](https://paste.gg/p/wphant0m/40996ccd3a41438a9dcafc1a06f906b2)
![image](https://user-images.githubusercontent.com/33400200/95685927-87efb180-0c03-11eb-9a33-6d543918f8bf.png)

**Comment by McJty** [comment]
I'll implement a workaround for this (it's actually a vanilla issue)

**Comment by MilesTFox** [comment]
Bump
