### ISSUE TITLE
Shape card in a shield projector does no damage.

### ISSUE THREAD

**Issue by PongoSapiens** [McJtyMods/RFToolsBuilder#33]
MC 1.16.3
Forge 34.1.42
McJtyLib 5.0.12
RFToolsBase 2.0.6
RFToolsBuilder 3.0.9

When you use a shape card in the Shield project and set the type to damage, no damage is done to anything in the shield.

**Comment by McJty** [comment]
What do you mean by 'in the shield'? Is the shape hollow or filled? The shield only does damage where there are shield blocks and a hollow shape only generates shield blocks at the border. Can you elaborate?

**Comment by PongoSapiens** [comment]
I've just tried to reproduce this and I can't. It was a solid box, for killing withers, and at the time I tested it several times and each time the wither took no damage. However it works perfectly now, so I'm guessing it was me making the same mistake repeatedly
I apologize for wasting your time with this.
