### ISSUE TITLE
Builder with "Shape Card (Placing Liquids)" crashes server.

### ISSUE THREAD

**Issue by PongoSapiens** [McJtyMods/RFToolsBuilder#34]
Minecraft 1.16.3
Forge 34.1.42
McJtyLib 5.0.13
RFTools Base 2.0.6
RFTools Builder 3.0.10

https://pastebin.com/gZ1pn7p6

100% repeatable and I've tried with mekanism tanks, rftools tank and several others.

**Comment by McJty** [comment]
Fixed next release
