### ISSUE TITLE
Shape cards with invalid state/nbt data

### ISSUE THREAD

**Issue by Obbi89** [McJtyMods/RFToolsBuilder#35]
I managed to brick the state of a shape card (this applies to the 1.15 branch)
This causes an issue disallowing you to select areas using the builder tile entity.

https://github.com/McJtyMods/RFToolsBuilder/blob/1c48f2d623a79d07ad51d344bd57eb5af54773c9/src/main/java/mcjty/rftoolsbuilder/modules/builder/items/ShapeCardItem.java#L146

This check is always true with NBT having mode set to 1 while selectedX,Y,Z coordinates do not exist.
I managed to create such a shape card by selecting a builder for shape mode -> mode = 1
Then change the type of the shape card by crafting a pump into a clearing pump or a quarry into a clearing quarry.
This seems to copy all the state information except selectedX,Y,Z over to the new card.

Imho the easier fix would be to always set mode to 0 while copying the state over when people craft between different types of shape cards. This won't fix already broken cards though. Maybe allow to reset mode to 0 by some other means or check the nbt for consistency?

**Comment by McJty** [comment]
Good catch. I'll fix this and also unbreak existing cards (by resetting mode to 0 if there is no selected x,y,z)

**Comment by McJty** [comment]
Will be fixed in the next update
