### ISSUE TITLE
Shield Template blocks

### ISSUE THREAD

**Issue by Based199** [McJtyMods/RFToolsBuilder#38]
So in the past versions of rftools, the shield template blocks recipe gave 8 per craft. However in the 1.16 version it only gives 1 per craft. Now i suppose this could be intended but as it stands to make even a hollow 7x7x7 it takes over 1k wool.

**Comment by McJty** [comment]
That's not intended. I'll fix this

**Comment by McJty** [comment]
Fixed for next release (soon)
