### ISSUE TITLE
Change replace block for mining

### ISSUE THREAD

**Issue by Goten87** [McJtyMods/RFToolsBuilder#42]
is there still a way to change the replace block when you use the mining card

if yes where can i change it i normaly have it course dirt and not normaal dirt

**Comment by Staegrin** [comment]
Serverconfig rftoolsbuilder-server.toml
#Use this block for the builder to replace with
	quarryReplace = "minecraft:stone"

I changed the minecraft:dirt to minecraft:stone. Sadly the replace block is still dirt. Is this intentional?

Version
rftoolsbuilder-1.18-4.0.13
forge 40.1.54
