### ISSUE TITLE
cant mine half chuncks

### ISSUE THREAD

**Issue by Goten87** [McJtyMods/RFToolsBuilder#44]
i want to mine out a half a chunk but the builder is not mining it out it leaves the blocks alone but it is scanning then and going down Y levels

**Comment by McJty** [comment]
ALWAYS specify the version you're using. This report is useless right now.

Also what exactly are you doing? Can you give more detailed information?

**Comment by Goten87** [comment]
i use `rftoolsbuilder-1.16-3.0.13` i like to mine out a lot of land under my house so i dont have caves anymore so i use a shape card (Clearing Quarry) now i had a part where i dint mine a whole chunk and it skips it and then when it hits a full chunk again it starts removing the blocks

**Comment by McJty** [comment]
Do you have a mod that claims chunks? In that case you have to tell that mod to also allow fake players

**Comment by Goten87** [comment]
ahh yes i use ftb utils or chunks or what the name now is lets see if i can fix that xD

**Comment by Goten87** [comment]
i was so confused but now it makes sense

**Comment by Goten87** [comment]
```
#Disables fake players like miners and auto-clickers.
disable_fake_players = false
``` 
its already false in my server setting file for ftbchunks

**Comment by McJty** [comment]
Try unclaiming the chunk

**Comment by Goten87** [comment]
i will try to remove the chunk claim when its done filling again and then see what that will do

**Comment by Goten87** [comment]
ok when i removed the chunk claim it worked but i also found how to add the fake player to the list you need to go to ally's when the builder is working then you can add him as a friend/ally so he can work on the claimed chunks so its fixed and i will close this now
