### ISSUE TITLE
[1.16.5] Skip Blocks the Builder can't break

### ISSUE THREAD

**Issue by NielsPilgaard** [McJtyMods/RFToolsBuilder#48]
When the Builder, equipped with a Quarry card, encounters a chest from the mod Lootr, it stops and fails to continue as it cannot break it. Lootr chests require the breaker to hold shift while breaking it. 

I would like to suggest simply skipping blocks whenever the builder finds something it can't break.

#### Context
https://github.com/NillerMedDild/Enigmatica6/issues/1927

**Comment by McJty** [comment]
Didn't the builder have an option for that already (check the gui buttons)?

**Comment by NielsPilgaard** [comment]
I totally missed that, yes it does, my bad 😄
