### ISSUE TITLE
The player name in the TAB player list changes to "rftools_builder" when a builder is active

### ISSUE THREAD

**Issue by iTitus** [McJtyMods/RFToolsBuilder#59]
![2021-07-08_11 28 11](https://user-images.githubusercontent.com/5154317/124898559-9aa2e580-dfdf-11eb-9614-6b47dc5611a0.png)

This is RFTools builder version 3.0.17 in ATM6 1.6.14 on a server.
Forge Version is 1.16.5-36.1.32

**Comment by McJty** [comment]
Fixed next release
