### ISSUE TITLE
Builder Pump Issue with replacement

### ISSUE THREAD

**Issue by iTitus** [McJtyMods/RFToolsBuilder#60]
RFTools builder version 3.0.17 in ATM6 1.6.14 on a server.
Forge Version is 1.16.5-36.1.32.

I have a builder with the pump card setup in the Nether. No clearing.
But the fluid blocks are not replaced with dirt.

The issue could be in McJtyLib:

https://github.com/McJtyMods/McJtyLib/blob/3e766e49f9dc22211f3df1ccdfc5ccc1de0ed8dc/src/main/java/mcjty/lib/varia/FluidTools.java#L116-L121

The lava block (`FlowingFluidBlock`) implements `IBucketPickupHander` and removes itself, but the `Runnable` for the replacement is not run in this case.

**Comment by McJty** [comment]
Should be fixed now. Sorry for the delay
