### ISSUE TITLE
I have 2 error

### ISSUE THREAD

**Issue by EmirLogas** [McJtyMods/RFToolsBuilder#61]
I have 2 error
1- Rftoolsbuilder encountered an error during the load_registries event phase          java.lang.IllegalArgumentException: block(null) has property: render with invalidly named value invisible.
2- rftoolsbuilder encountered an error during the error event phase            java.lang.nullpointerexception: registry object not present: rftoolsbuilder :shielding_solid

**Comment by McJty** [comment]
Please more info. Version, full logs

**Comment by EmirLogas** [comment]
[latest.log](https://github.com/McJtyMods/RFToolsBuilder/files/6818799/latest.log)
[crash-2021-05-10_20.53.47-fml.txt](https://github.com/McJtyMods/RFToolsBuilder/files/6818800/crash-2021-05-10_20.53.47-fml.txt)

**Comment by McJty** [comment]
What other mods do you have?

**Comment by EmirLogas** [comment]
When I try this mod alone I get the error. It used to happen in Cyclic but it was fixed in the last version.

**Comment by McJty** [comment]
Alone? You do need mcjtylib and rftoolsbase. Those are required
