### ISSUE TITLE
builder with space card to swap chest behind builder with space chamber with chest in middle

### ISSUE THREAD

**Issue by DoomSquirter** [McJtyMods/RFToolsBuilder#62]
playing in 1.16 (enigmatica 6)

I did this for first time playing multiblock madness (1.12)
made a space chamber around a chest, linked it to a space card, and put the card in the builder with a chest behind it.  configure builder to move entities and set to swap.  send redstone and it'd swap both chests.

when I do this here in 1.16 tho, I rclick the space card after I link it and it says the chest is "UNMOVABLE!"

did this behavior get removed in 1.16? or changed somehow?

I'm using the following:
rftoolsbase-1.16-2.0.11
rftoolsbuilder-1.16-3.1.0
rftoolscontrol-1.16-4.0.11
rftoolsdim-1.16-7.0.11-beta
rftoolspower-1.16-3.0.9
rftoolsstorage-1.16-2.0.12
rftoolsutility-1.16-3.1.0

also, side note chuckle and not important but funny nonetheless.  
I had my other builder quarrying out an area and due to something else entirely, server crashed.
when I relogged in, my name was changed to RFTOOLS_BUILDER 
lmao
https://cdn.discordapp.com/attachments/103277907828277248/868673364854726696/unknown.png

**Comment by McJty** [comment]
Hmm strange. this works for me. Can you show a screenshot of the gui for the space card?

**Comment by DoomSquirter** [comment]
https://i.imgur.com/NV406uf.png

also, now, I've noticed that every time server restarts (so far always crashes unrelated to rftools) I am still being called rftools_builder each time lol.   it's only in the server tab menu.  ppl still see my correct name in chat, etc

**Comment by McJty** [comment]
Strange. Works fine for me. You didn't modify any configs to make moving chests not possible?

**Comment by DoomSquirter** [comment]
I checked the ./configs directory config for builder and nothing looked out of the ordinary.  don't know if pack maker did and I don't have access to the server's save directory if you store a .toml or other file in there.  If you say it's supposed to work then I assume that a config was changed.  

if you can point me to where exactly I should look for said change, that'd be extremely helpfull

**Comment by DoomSquirter** [comment]
I am going to assume at this point it was something the modpack makers did to overcome an issue with special chests in the game.  updated pack and problem went away.  Problem is not on your end.  Thanks for your attention tho.  it's appreciated.
