### ISSUE TITLE
[1.16.5] Builder collector ignoring whitelist filter

### ISSUE THREAD

**Issue by CodeGordon** [McJtyMods/RFToolsBuilder#63]
The builder in collect mode is collecting everything in range, even with a filter applied.

The filter config:
![2021-07-25_16 28 32](https://user-images.githubusercontent.com/7526525/126912622-49d7d482-3318-403a-a74e-43edec1e7c31.png)

The builder setup, including the above filter installed:
![2021-07-25_16 28 50](https://user-images.githubusercontent.com/7526525/126912629-f69b5564-c730-47e2-ac55-0207a2ec5b61.png)

**Comment by McJty** [comment]
The filter does not work for collect. It's only meant for the quarry. Could be a feature. Also what version?

**Comment by CodeGordon** [comment]
Base 2.0.11 and Builder 3.1.0 with Forge version 36.1.32.

I would never refer to such non-interaction as a feature, but as either a bug or an oversight. The description on the filter and what documentation is in the in-game book, along with the fact that the builder includes the filter slot that isn't greyed out or whatever when set to collect, all point to filters being useful for such function. They really ought to be, because that's the intuitive expectation and introduces some nice possibilities for pre-storage sorting.

**Comment by McJty** [comment]
It's definitely a feature. The item filter was only intended to be used for the quarry. I'll consider implementing it also for the item collector though as indeed that's a useful thing to have

**Comment by McJty** [comment]
Implemented for the next release

**Comment by CodeGordon** [comment]
Thank you for the quick turnaround. It's working great. :D
