### ISSUE TITLE
Builder getting stuck on blocks despite blocks being blacklisted in filter

### ISSUE THREAD

**Issue by NielsPilgaard** [McJtyMods/RFToolsBuilder#64]
I've filtered my Builder Quarry to blacklist chests from the mod loot, and despite this, the Builder gets stuck when it gets to one. I was expecting it to skip past it.

I have also tried in whitelist mod, and with damage/nbt/mod filtering on and off in every combination pretty much.

### Versions
- rftoolsbuilder-1.16-3.1.0

**Comment by McJty** [comment]
What are you doing with the builder exactly? What operation?

**Comment by NielsPilgaard** [comment]
I'm trying to Quarry an area which has a Lootr chest inside it. The Builder Quarry is unable to break the Lootr chest, so I added a filter to blacklist Lootr chests.

**Comment by McJty** [comment]
Hmm. I cannot reproduce this. I think the builder is configured weirdly in Enigmatica. But did you try pressing this button:

![image](https://user-images.githubusercontent.com/8188472/127162457-9bef0421-865d-4f1a-bf4d-d15f1dd17246.png)

**Comment by NielsPilgaard** [comment]
Did you try to reproduce it with a Lootr chest specifically? 

I did try pressing that button, I should've mentioned that in the initial report ^^'

It does skip it correctly when waiting is off, but then it won't wait if it's inventory is full either. I just want it to ignore the Lootr chest like the filter specifies :<

**Comment by NielsPilgaard** [comment]
Here's our RFTools Builder config btw, in case that helps: https://github.com/NillerMedDild/Enigmatica6/blob/develop/defaultconfigs/rftoolsbuilder-server.toml

**Comment by McJty** [comment]
A loot chest is just a chest. Shouldn't make a difference

**Comment by McJty** [comment]
Oh
	tileEntityMode = "MOVE_WHITELIST"

Enigmatica sets the mode to whitelist. That's why.
Set it back to the default BLACKLIST if you want it to work properly

**Comment by NielsPilgaard** [comment]
Huh, I have no memory of ever changing that config, odd. However, setting it to `MOVE_BLACKLIST` for my test instance didn't change anything :/

It's not just a loot chest, it's a Loot Chest from the mod Lootr. https://www.curseforge.com/minecraft/mc-mods/lootr
I'm guessing it's a tile entity.

**Comment by NielsPilgaard** [comment]
After a few more restarts it's now behaving as I would like - The Builder can skip the Lootr Loot Chest, and still stops when out of inventory space.

Thanks for your help!
