### ISSUE TITLE
I put a builder in floor and crash my game.

### ISSUE THREAD

**Issue by HenriqueMairesse** [McJtyMods/RFToolsBuilder#65]
I put in a block a builder and my game crashed, after I try to open minecraft and join the world again and crash the moment load. I try to ask support, but I saw a new version and I install and launch my world again, but crash in the moment load. I don't know I only put in the floor. Here is rfmods I use and versions: https://prnt.sc/1gw6bmb. Minecraft version: 1.16.5 Forge version: 36.2.0. McJtyLib: 5.0.21. I will submit the 3 crash logs here. Thanks.
[crash-2021-07-27_23.08.59-client.txt](https://github.com/McJtyMods/RFToolsBuilder/files/6890047/crash-2021-07-27_23.08.59-client.txt)
[crash-2021-07-27_23.35.56-client.txt](https://github.com/McJtyMods/RFToolsBuilder/files/6890048/crash-2021-07-27_23.35.56-client.txt)
[crash-2021-07-28_00.02.18-client.txt](https://github.com/McJtyMods/RFToolsBuilder/files/6890049/crash-2021-07-28_00.02.18-client.txt)

**Comment by McJty** [comment]
Do you have the latest version of mcjtylib, rftoolsbase, and rftoolsbuilder?

**Comment by HenriqueMairesse** [comment]
I download the mods 2 days ago and in the third crash I use the latest version of rftools builder, but I check now and the mcjtylib uptade 15 hours ago and I don't update only this mod, I will try in 11 hours with mcjtylib last uptade, because I will sleep now.

**Comment by HenriqueMairesse** [comment]
The new version of mcjtylib fix that, sorry for this.
