### ISSUE TITLE
java.lang.AbstractMethodError: Method mcjty/rftoolsbuilder/modules/builder/blocks/BuilderTileEntity.getBlockPos()Lnet/minecraft/util/math/BlockPos; is abstract

### ISSUE THREAD

**Issue by Nicolasito52** [McJtyMods/RFToolsBuilder#68]
Hello, sorry to bother you, but I have all the rftools mods up to date, and yet, when I put the BuilderBlock my game crashes with this error "The game crashed while rendering block entity
Error: java.lang.AbstractMethodError: Method mcjty/rftoolsbuilder/modules/builder/blocks/BuilderTileEntity.getBlockPos()Lnet/minecraft/util/math/BlockPos; is abstract". Is this a bug? Thanks in advance

**Comment by Nicolasito52** [comment]
Here is the list of mods

![image](https://user-images.githubusercontent.com/89771045/131482415-a01ad6cc-ff24-4987-9788-4027ee31d118.png)

**Comment by McJty** [comment]
Update McJtyLib

**Comment by Nicolasito52** [comment]
I have the latest version of McJtyLib on Cursforge, should I download the mod somewhere else?

**Comment by McJty** [comment]
No no
What's the version of RFToolsBase?

**Comment by McJty** [comment]
NEVER download my mods from anywhere else

**Comment by Nicolasito52** [comment]
Actually, I don't know, I think that's the problem, when the version is not displayed it means that the mod is not from Cursforge, so I must not have the right version. Sorry to have bothered you for that.

**Comment by McJty** [comment]
yes, best to get RFToolsBase from CurseForge

**Comment by Nicolasito52** [comment]
indeed it solved the problem, thank you
