### ISSUE TITLE
Crash when system locale is Turkish or similar

### ISSUE THREAD

**Issue by sam-kirby** [McJtyMods/RFToolsBuilder#73]
The crash is a direct result of the linked line: https://github.com/McJtyMods/RFToolsBuilder/blob/1.16/src/main/java/mcjty/rftoolsbuilder/modules/shield/ShieldRenderingMode.java#L46

The use of String#toLowerCase without specifying a locale can give unexpected results when the system locale is Turkish, which returns `ı`, a "dotless i", as the lower case equivalent of `I`. See [here](https://stackoverflow.com/questions/11063102/using-locales-with-javas-tolowercase-and-touppercase) for more information.

`ı` is not valid in a property value, and so the game crashes with the linked report.

Consider forcing the locale to be ROOT or ENGLISH when doing this lower case transform, or getting rid of the capitalised strings.

[crash.txt](https://github.com/DarkPacks/SkyFactory-One/files/7446424/crash.txt)

First reported: DarkPacks/SkyFactory-One#109

**Comment by berksedatk** [comment]
Can reproduce, I had to remove the mod from the pack for now.
![Screenshot 2022-02-26 170330](https://user-images.githubusercontent.com/30241194/155846132-6ce02d68-82bf-42b6-a5de-815d84f99084.png)

**Comment by McJty** [comment]
Will be fixed next release
