### ISSUE TITLE
Shield Projector seems to be broken

### ISSUE THREAD

**Issue by MojangPlsFix** [McJtyMods/RFToolsBuilder#76]
As described in AllTheMods/ATM-6#2778. After updating to the newest version, the shield generators broke down.
Our Users crash with:
https://gist.github.com/fabrossmann/b98d27164875b680ad34bdddaa22d717

On the server side we get the same exception:
https://gist.github.com/fabrossmann/12d26d545218b824c13b26374255807a

On a note: We have added Roadrunner to our server, removing the mod, results into the same problem.
On another note: This exception and crash, does not respect the "removeErroringTileEntities" config of Forge.

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Will be fixed next release (soon)
