### ISSUE TITLE
[1.18.1] Quarry and Pump Card World Height Issue

### ISSUE THREAD

**Issue by trogarus** [McJtyMods/RFToolsBuilder#81]
Minecraft 1-18-1
Forge 39.0.59
McJtyLib 1.18-6.0.8
RFToolsBuilder 1.18-4.0.5

Quarry and pump cards don't seem to recognize new world height. If I run the quarry/pump at y75, for example, it only quarry and pumps to -54. Height slot is still defaulting to old world height pre 1.18 (256). If I move the quarry/pump lower in the world, it will correctly remove blocks and fluids to bedrock. This also causes a problem in amplified areas where you have to run the quarry/pump multiple times at different y levels to completely clear an area. Dirt replacement of fluids is also glitchy still. The quarry doesn't seem to be placing dirt at all like it used to. This results in source blocks left behind in larger water areas.

Thanks for the mods you maintain. I've used them for years of play through various versions of minecraft all the way back to 1.7.

**Comment by McJty** [comment]
I'll check it out

**Comment by BrewingCoder** [comment]
This is still present in the DW20 1.18.2 pack that uses version rftoolsbuilder-1.18-4.0.10

**Comment by BrewingCoder** [comment]
If the quarry cards could support more than 256 Y Levels that would resolve the issue.

Otherwise a workaround is to take the builder down below a Y level sufficient to mine all the way down

**Comment by McJty** [comment]
As far as I know this was resolved a while ago
