### ISSUE TITLE
[1.18] Shield Projector Requires GUI Update to be Reactivated

### ISSUE THREAD

**Issue by Brown-bricks** [McJtyMods/RFToolsBuilder#83]
When a shield projector is powered on by redstone, powered off, and then powered on again, it does not reactivate. This can only be fixed by changing a setting in its GUI.

Custom Modpack
Minecraft 1.18.1
Forge 39.0.57
McJtyLib-1.18-6.0.8
rftoolsbuilder-1.18-4.0.5

Full list of mods available on request.

**Comment by ItsEgmxn** [comment]
ı have this Issue too

**Comment by McJty** [comment]
Fixed in the next release (later today)
