### ISSUE TITLE
Enabling Previews causes crash on singleplayer.

### ISSUE THREAD

**Issue by Brown-bricks** [McJtyMods/RFToolsBuilder#84]
Enabling a preview on a builder causes a crash on 1.18. Seems to be a caused by an aspect of the GUI that's supposed to be server-side being handled client-side or vice-versa. Log is below.

Custom Modpack
Minecraft 1.18.1
Forge 39.0.57
McJtyLib-1.18-6.0.8
rftoolsbuilder-1.18-4.0.5

[crash-2022-02-09_17.58.59-client.txt](https://github.com/McJtyMods/RFToolsBuilder/files/8054619/crash-2022-02-09_17.58.59-client.txt)

**Comment by McJty** [comment]
Fixed in the latest release
