### ISSUE TITLE
Builder showing "Break was cancelled" error.

### ISSUE THREAD

**Issue by jamesfoster** [McJtyMods/RFToolsBuilder#85]
Hi, I've set up an RFTools Builder and it runs for quite a while, but eventually it displays the "Break was cancelled" error and stops running.

In case it has something to do with claimed chunks I've allowed Fake Player interaction and set the block interaction to Public (defaults to Allies only)

I'm running Enigmatica 8 v1.0.5 and the version targeted is rftoolsbuilder-1.18-4.0.5

TIA

**Comment by McJty** [comment]
yes, that has something to do with claimed chunks. You would have to try to figure out where it is stopping exactly

**Comment by jamesfoster** [comment]
Would the ideal behaviour be to skip breaking those blocks and continue running? Given there's no "Continue from where you left off" button.

**Comment by McJty** [comment]
Well you can enable that option from the builder gui
