### ISSUE TITLE
Builder with Fortune Quarry not breaking blocks only replacing stone with dirt.

### ISSUE THREAD

**Issue by tylerwoods22** [McJtyMods/RFToolsBuilder#87]
Issue description: My builder with fortune quarry is outputting ores and blocks it mines to the chest above my builder but no blocks are actually being broken. As shown in my screenshot it just removes grass and replaces stone with dirt. The builder was working with my modpack flawlessly and this issue just arose out of nowhere. My modpack had the latest version RFToolsBuilder 1.16-3.1.7. I have tried to downgrade to the version below that but the issue still arises.

The builder also seems to never receive enough power even if I use creative unlimited energy.

Steps to reproduce: I have re built my quarry setup in multiple locations and worlds. If you watch a video (https://youtu.be/WwrZjBaDTSc) I made showing the issue you can see it even places dirt in some areas and still finds ores and cobblestone but nothing is ever really broken. 

Versions:
* Minecraft: 1.16.5
* Forge: 36.2.29
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.16-5.1.4
* RFToolsBuilder: RFToolsBuilder 1.16-3.1.7

**Comment by McJty** [comment]
Closed why? What was happening?

**Comment by tylerwoods22** [comment]
I stupidly was using the wrong shape card. I didn't realize there was a clearing quarry and quarry card. the fortune quarry card was replacing everything it mined with dirt. I found the clearing quarry card in and it continued to remove the blocks like I wanted.
