### ISSUE TITLE
Builder copying twice

### ISSUE THREAD

**Issue by R3PTR** [McJtyMods/RFToolsBuilder#89]
While playing AllTheMods7 1.18.2 on a Server I ran into an issue with the Builder. I tried to copy a simple structure and the builder copied it twice. I was able to recreate the issue in single player. I took a video and uploaded it unlisted to youtube: https://youtu.be/71-QLU7DCbk .

**Comment by McJty** [comment]
I have not been able to reproduce this. It might be an interaction with another mod but I have no clue what

**Comment by McJty** [comment]
Has been fixed some time ago
