### ISSUE TITLE
fortune and silk touch not applied by builder

### ISSUE THREAD

**Issue by Willy347** [McJtyMods/RFToolsBuilder#9]
mc 1.15 forge 31.1.19
rftoolsbase -1.15-1.0.0-alpha.jar
rftoolsbuilder -1.15-2.0.0-alpha.jar

don't know if it just isn't implemented yet or a bug.
silk quarry and clearing silk quarry don't apply silk touch.
fortune quarry and clearing fortune quarry don't apply fortune

**Comment by LuciusV** [comment]
For version 1.15-2.1.1-beta.jar it uses silk touch normally, except for Rock Salt from XP Food Mod (I'm pretty sure it was applying in 1.12.2). Fortune not tested

**Comment by McJty** [comment]
Will be fixed next release. Was actually a combination of two bugs
