### ISSUE TITLE
1.18.2 Shield Projector Requires GUI Update to be Reactivated

### ISSUE THREAD

**Issue by ItsEgmxn** [McJtyMods/RFToolsBuilder#91]
When a shield projector is powered on by redstone, powered off, and then powered on again, it does not reactivate. This can only be fixed by changing a setting in its GUI
Mods;
Security Craft
Create
FlyWheel
jei
optifine
RFTools Base
RFTools builder
RFTools Power
McJtyLib

**Comment by TheFantasticLoki** [comment]
I also experience this and it limits the functionality a lot.

**Comment by sdrush** [comment]
I have the same issue with the latest rftools on 1.18.2 as well.

**Comment by McJty** [comment]
Checking this out now

**Comment by McJty** [comment]
Will be fixed next release (later today)
