### ISSUE TITLE
Builder compatibility for Dadobug1111's Bedrock Ores

### ISSUE THREAD

**Issue by dadobug1111** [McJtyMods/RFToolsBuilder#92]
The Builder breaks bedrock ores once and sets block to air. Bedrock ores are not suppose to turn to air when broken, instead they can be broken infinitely without losing the block.

if you put lines 1087 - 1091 of [RFToolsBuilder/src/main/java/mcjty/rftoolsbuilder/modules/builder/blocks/BuilderTileEntity.java](https://github.com/McJtyMods/RFToolsBuilder/blob/1.18/src/main/java/mcjty/rftoolsbuilder/modules/builder/blocks/BuilderTileEntity.java) in an if statement that only runs if srcState is NOT in [Exclusion Block Tag], that _should_ allow me to add my blocks to the tag and fix it, if I am reading the code right.

Thank you for considering this!

https://github.com/dadobug1111/DadobugBedrockOres - The mod in question

**Comment by McJty** [comment]
In the next version there will be a new tag rftoolsbuilder:dontremoveme that you can use for this
