### ISSUE TITLE
1.18.2 Blocks quarried by the Builder with tag "dontremoveme" don't use any power in the builder

### ISSUE THREAD

**Issue by Raidobw2** [McJtyMods/RFToolsBuilder#99]
Hello, it appears blocks quarried by the RFTools Builder with either a Fortune Quarry or Clearing Fortune Quarry with the tag "rftoolsbuilder:dontremoveme" actually don't use any power from the builder, but still provide block drops.

I have not tested with other quarry cards such as the normal card or Silk Touch, but I assume the same thing is going on there.

Versions:
Minecraft `1.18.2`
Forge `40.1.51`
RFTools Builder `rftoolsbuilder-1.18-4.0.12.jar`
RFTools Base `rftoolsbase-1.18-3.0.8.jar`
McJtyLib `mcjtylib-1.18-6.0.14.jar`
Bedrock Ores `dadobugbedrockores-1.3.6-forge.jar`

Example:

https://user-images.githubusercontent.com/17010632/174459484-17e60a4a-8c36-4080-bf56-be0d1e4ca867.mp4

I would like to suggest making the Builder use power despite those blocks like Bedrock Ores be infinite. That means the block would not disappear in the world, you would receive the drops, but the Builder would still use a considerable amount of power based on the hardness of the block.

Linked to #92

Thanks in advance for looking into it, and have a good weekend as well

**Comment by McJty** [comment]
Fixed next release (this evening probably)
